[phases.setup]
nixPkgs = ["python311", "gcc", "openssl", "libffi"]

[phases.install]
cmd = "pip install --upgrade pip && pip install -r requirements.txt"

[start]
cmd = "python manage.py migrate && gunicorn ecomsite.wsgi:application"
